### ISSUE TITLE
Python error when starting 2.12 or 2.10

### ISSUE THREAD

**Issue by dickwall** [kartoza/docker-qgis-desktop#10]
Just tried to create latest, 2.12 and 2.10 on my machine (haven't tried the others yet, so don't know if they exhibit the same behavior or not).

QGIS runs, but with the following error on startup:

```
Couldn't load plugin 'processing' from ['/usr/share/qgis/python', '/home/dick/.qgis2/python', 
'/home/dick/.qgis2/python/plugins', '/usr/share/qgis/python/plugins', '/usr/lib/python2.7', 
'/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', 
'/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', 
'/home/dick/.qgis2//python']
```

Looking on the goog, it looks like this is some kind of pyqt4 or scintilla problem possibly. I am happy to put in the legwork for fixing if someone can point me in the right direction. Is this something I need on my local machine or in the docker container (it sort of looks like it might need fixing locally). I am running ubuntu 15.10 if that helps debug.

Thanks

**Comment by luipir** [comment]
hi dick

**Comment by luipir** [comment]
Hi dickwall... it was a fresh docker install or did you update Processing plugin after run qgis?

**Comment by dickwall** [comment]
Hi there - fresh docker install after following the instructions exactly in 2.10 folder. Specifically:

```
docker pull kartoza/qgis-desktop:2.10
sudo cp run-qgis-2.10-in-docker.sh /usr/local/bin
sudo cp QGIS-2.10.Docker.desktop /usr/share/applications/
sudo cp qgis-icon-60x60.png /usr/local
/usr/local/bin/run-qgis-2.10-in-docker.sh
```

Hope that helps.

Thanks

**Comment by timlinux** [comment]
I tested here with the latest 2.14 - can you try again and re-open this issue if there is still an issue?
