### ISSUE TITLE
I found a way to not use 'xhost'

### ISSUE THREAD

**Issue by timcera** [kartoza/docker-qgis-desktop#16]
There is a way where you don't use xhost.  You have to run as the same user within the image as you use to run the image.  I use and environment variable to pass that information into the image.

If interested take a look at timcera/qgis-desktop-debian.

Thanks for setting this up.  Your work was my initial guide.

**Comment by timlinux** [comment]
Hi @timcera 

Thanks for your tips! - I will update the readme!

Regards

Tim
