### ISSUE TITLE
Container complains about no start.sh

### ISSUE THREAD

**Issue by ConorIA** [kartoza/docker-qgis-desktop#22]
When I try to run the container, it complains that there is no start.sh script to run. It seems it was dropped from the Dockerfiles in this commit c2489be6fb0a508f6a0ea0418f2375e03c6ab703.

The following is the code I was trying to run: 
```
docker run --rm --name="qgis-desktop-ltr" \
	-i -t \
	-v ${HOME}:/home/${USER} \
	-v /tmp/.X11-unix:/tmp/.X11-unix \
	-e DISPLAY=unix$DISPLAY \
	kartoza/qgis-desktop:2.14.6
```

**Comment by seifer08ms** [comment]
I am getting the similar error with the same running command:
`docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"/start.sh\\\": stat /start.sh: no such file or directory\"\n".`

**Comment by ConorIA** [comment]
I started taking on the problem in #23, but it wasn't perfect. If you want a quick solution (and don't mind pre-built packages), try https://github.com/ConorIA/dockerfiles/tree/master/qgis.

**Comment by seifer08ms** [comment]
@ConorIA 
Thanks! I copied your correction from your pull request, and it works now while it still complains missing some python plugins.

**Comment by ConorIA** [comment]
@seifer08ms, if you can let me know what plugins are missing, I can see about adding them to the PR.
