### ISSUE TITLE
User issue

### ISSUE THREAD

**Issue by brunorpinho** [kartoza/docker-qgis-desktop#25]
I am just starting with docker and I am trying to run a docker container, but this user issue just keep happening. Any ideas on how to fix this?

```
$ docker run --rm --name="qgis-desktop-2.18ltr" -t -i -v '/windows/Bruno/Engenharia Geologica/TCC' -e DISPLAY=unix$DISPLAY kartoza/qgis-desktop:2.18.10

groupadd: GID '0' already exists
useradd: UID 0 is not unique
No passwd entry for user '..'
```

**Comment by brunorpinho** [comment]
I figured out that the code in `start.sh` is selecting the wrong folder. For some reason I have two folders in the `home` directory: `bruno` and `lost+found`. `lost+found` appears to be a system folder.

It is cool to select the last entry of the tail, but `lost+found` has to be ignored since it is a system folder.

These are the commands in the `start.sh` file:

```
#!/bin/bash

# Put any tasks you would like to have carried
# out when the container is first created here

# We expect the container is started with the
# the users ~ directory mounted as /home/$USER

# Make the user matching the user from the mounted home
# We assume there will only be one user dir in home
# hence tail -1
USER_ID=`ls -lahn /home | tail -1 | awk {'print $3'}`
GROUP_ID=`ls -lahn /home | tail -1 | awk {'print $4'}`
USER_NAME=`ls -lah /home/ | tail -1 | awk '{print $9}'`
```

**Comment by Gustry** [comment]
Sorry for the late answer. Feel free to provide a patch or to open a ticket for a feature request.

**Comment by brunorpinho** [comment]
Hello @Gustry, thanks!

I put it to work now, I was just missing some basic concepts of docker. This is why I closed the issue.

Using QGIS without installing two hundred packages in my system feels brilliant.
Thanks!
