### ISSUE TITLE
osgeo [python-gdal] mdule is missing

### ISSUE THREAD

**Issue by Bakaniko** [kartoza/docker-qgis-desktop#27]
Hi, when I run the 2.18.12 and 2.14.16 images I encounter this error:

![image](https://user-images.githubusercontent.com/17683898/29946050-099c6be6-8ea4-11e7-8d5b-393fb777db0d.png)

There is after that a message that the processing and metasearch plugins can't be load (I think it is related)

QGIS works quite well but the python console is not working. 

![image](https://user-images.githubusercontent.com/17683898/29959541-2c4b93f2-8ef8-11e7-9695-1ac49c842878.png)

I think it is because I don't have any spatial library (and especially GDAL) on the python installation from the host machine. 
I'm running on a fresh ubuntu mate 16.04.3 with python 2.7.12

Is there a way to install it on the docker image ? Or do I have to install it on my host python ?
How can I do that ?

Please note that for the 2.14 image I didn't encounter this error and the python console works pretty well.

For the moment I only tested those 3 images only.

Thanks,

Nicolas

**Comment by valpesendorfer** [comment]
Hi @Bakaniko , 

I've experienced the same issue, along with a bunch of other missing dependencies. You don't need to change anything on your host machine, the dependencies are missing within the Ubuntu container which should run qgis.

For a hotfix I just modified the `getDeps.sh` script and added all missing dependencies. Feel free to check it out on my [fork](https://github.com/valpesendorfer/docker-qgis-desktop/blob/develop/2.14/build/getDeps.sh). 

I'm not sure if you need all the modifications I made, but I also started out with the osgeo problem and after fixing that the plugin errors just kept coming. With the current setup it's working fine for me.


HTH

**Comment by Bakaniko** [comment]
Thanks @valpesendorfer I'll be looking at that :)

**Comment by Bakaniko** [comment]
Thanks @valpesendorfer I'll be looking at that :)
