### ISSUE TITLE
Qgis-desktop with windows

### ISSUE THREAD

**Issue by Soleferry** [kartoza/docker-qgis-desktop#8]
Hi !
I've tried, following your guide, to setup docker-qgis-desktop in my windows environment. Unfortunately i haven't succeed this way...

Do you have an idea if this image can work on docker-windows and how ?

Thanks !

**Comment by timlinux** [comment]
Hi

I don't have a windows machine handy to test, but you would need to use an X-server client e.g. one of of  the tools from a search like this:

https://www.google.com/search?client=safari&rls=en&q=free+x+server+for+windows&ie=UTF-8&oe=UTF-8
