### ISSUE TITLE
container won't start on osx

### ISSUE THREAD

**Issue by grgurev** [kartoza/docker-qgis-desktop#9]
Hello,

when trying to start container from mac (capitan) I get following errors:

`bash-4.3$ docker run --rm --name="qgis-desktop-2.12" -i -t -v ${HOME}:/home/${USER} -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY kartoza/qgis-desktop:latest`
`groupadd: GID '50' already exists`
`bash: /usr/local/qgis-master/bin/qgis: No such file or directory`

I'm pulling image from the docker hub. Any idea why container is not starting?

Marin

**Comment by timlinux** [comment]
Hi

Please see my article [here](http://kartoza.com/how-to-run-a-linux-gui-application-on-osx-using-docker/) to explain how you can run under OSX. Basically you need a working X11 environment to use this.

Regards

Tim
